CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- CREATE Tables

CREATE TABLE organizations (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE users (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  organization_id uuid REFERENCES organizations(id),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE services (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  organization_id uuid REFERENCES organizations(id),
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE versions (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  service_id uuid REFERENCES services(id),
  version VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CREATE Indexes

CREATE INDEX ON services (name);
CREATE INDEX ON services (description);
CREATE INDEX ON services (created_at);

CREATE INDEX ON versions (service_id);
CREATE INDEX ON versions (version);


-- ADD Data

INSERT INTO organizations (name, description) VALUES ('Marelli', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO organizations (name, description) VALUES ('Bosch', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');

INSERT INTO users (organization_id, name, email, password) VALUES ((SELECT id FROM organizations WHERE name = 'Marelli'), 'John Doe', 'john.doe@mail.com', '');
INSERT INTO users (organization_id, name, email, password) VALUES ((SELECT id FROM organizations WHERE name = 'Bosch'), 'Jane Doe', 'jane.doe@mail.com', '');

INSERT INTO services (name, description, organization_id) VALUES ('Locate Us', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('Collect Monday', '', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('Contact Us', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('About Us', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('FX Rate International', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('FX Rate Local', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('FX Rate', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('FX Rate Calculator', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('FX Rate Converter', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('Notifications', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Marelli'));
INSERT INTO services (name, description, organization_id) VALUES ('News', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Bosch'));
INSERT INTO services (name, description, organization_id) VALUES ('Priority Issues', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Bosch'));
INSERT INTO services (name, description, organization_id) VALUES ('Feedback', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Bosch'));
INSERT INTO services (name, description, organization_id) VALUES ('Reporting', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Bosch'));
INSERT INTO services (name, description, organization_id) VALUES ('Security', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.', (SELECT id FROM organizations WHERE name = 'Bosch'));

INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '1.0.0', 'Initial version of Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '1.0.1', 'Added new feature to Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '1.0.2', 'Fixed bug in Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '1.11.0', 'Added new feature to Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '1.12.0', 'Fixed bug in Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '2.0.0', 'Added new feature to Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '2.1.0', 'Fixed bug in Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '2.2.0', 'Added new feature to Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '2.3.0', 'Fixed bug in Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '2.4.0', 'Added new feature to Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '2.5.0', 'Fixed bug in Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Locate Us'), '2.6.0', 'Added new feature to Locate Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');

INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.0', 'Initial version of Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.1', 'Added new feature to Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.2', 'Fixed bug in Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.3', 'Added new feature to Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.4', 'Fixed bug in Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.5', 'Added new feature to Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.6', 'Fixed bug in Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.7', 'Added new feature to Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.8', 'Fixed bug in Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.9', 'Added new feature to Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.0.10', 'Fixed bug in Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '1.12.0', 'Added new feature to Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '2.0.0', 'Fixed bug in Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '2.1.0', 'Added new feature to Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '2.2.0', 'Fixed bug in Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '2.3.0', 'Added new feature to Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Collect Monday'), '3.0.0', 'Fixed bug in Collect Monday service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');

INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '1.0.0', 'Initial version of Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '2.0.1', 'Added new feature to Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '2.0.2', 'Fixed bug in Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '2.0.3', 'Added new feature to Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '3.0.0', 'Fixed bug in Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '3.0.1', 'Added new feature to Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '4.0.0', 'Fixed bug in Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '4.0.1', 'Added new feature to Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '4.0.2', 'Fixed bug in Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '5.0.0', 'Added new feature to Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '5.0.1', 'Fixed bug in Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '5.0.2', 'Added new feature to Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '5.0.3', 'Fixed bug in Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '5.1.0', 'Added new feature to Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Contact Us'), '5.1.1', 'Fixed bug in Contact Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');

INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '1.0.0', 'Initial version of About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '1.0.1', 'Added new feature to About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '1.0.2', 'Fixed bug in About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '1.0.3', 'Added new feature to About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '1.0.4', 'Fixed bug in About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '1.0.5', 'Added new feature to About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '1.0.6',  'Fixed bug in About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '2.0.0', 'Added new feature to About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '2.0.1', 'Fixed bug in About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '2.1.0', 'Added new feature to About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '2.2.0', 'Fixed bug in About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '2.3.0', 'Added new feature to About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '2.4.0', 'Fixed bug in About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '3.0.0', 'Added new feature to About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '3.1.0', 'Fixed bug in About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '3.2.0', 'Added new feature to About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '3.3.0', 'Fixed bug in About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'About Us'), '3.4.0', 'Added new feature to About Us service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');

INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.0.0', 'Initial version of FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.0.1', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.0.2', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.0.3', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.0.4', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.0.5', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.1.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.2.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.3.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.4.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.5.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.6.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.7.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.8.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.9.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.10.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.11.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '1.12.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.0.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.1.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.2.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.3.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.4.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.5.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.6.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.7.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.8.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.9.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.10.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.11.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '2.12.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '3.0.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '3.1.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '3.2.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '3.3.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '3.4.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '3.5.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '4.0.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '4.1.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '4.2.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '4.2.1', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '4.2.2', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '5.0.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '5.1.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '5.2.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '5.3.0', 'Added new feature to FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate International'), '5.4.0', 'Fixed bug in FX Rate International service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');

INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.0.0', 'Initial version of FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.0.1', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.0.2', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.0.3', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.0.4', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.0.5', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.1.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.2.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.3.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.4.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.5.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.6.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.7.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.8.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.9.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.10.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.11.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '1.12.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '2.0.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '2.1.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.0.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.0.1', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.0.2', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.0.3', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.0.4', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.0.5', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.1.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.2.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.3.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.4.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.5.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.6.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.7.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.8.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.9.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.10.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.11.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '3.12.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.0.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.0.1', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.0.2', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.0.3', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.0.4', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.0.5', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.1.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.2.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.3.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.4.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.5.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.6.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.7.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.8.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.9.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.10.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.11.0', 'Fixed bug in FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Local'), '4.12.0', 'Added new feature to FX Rate Local service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');

INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.0.0', 'Initial version of FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.0.1', 'Added new feature to FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.0.2', 'Fixed bug in FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.0.3', 'Added new feature to FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.0.4', 'Fixed bug in FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.1.0', 'Added new feature to FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.2.0', 'Fixed bug in FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.3.0', 'Added new feature to FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.4.0', 'Fixed bug in FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.5.0', 'Added new feature to FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.6.0', 'Fixed bug in FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate'), '1.7.0', 'Added new feature to FX Rate service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');

INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Calculator'), '1.0.0', 'Initial version of FX Rate Calculator service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'FX Rate Converter'), '1.0.0', 'Initial version of FX Rate Converter service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Notifications'), '1.0.0', 'Initial version of Notifications service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'News'), '1.0.0', 'Initial version of News service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Priority Issues'), '1.0.0', 'Initial version of Priority Issues service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Feedback'), '1.0.0', 'Initial version of Feedback service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Reporting'), '1.0.0', 'Initial version of Reporting service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
INSERT INTO versions (service_id, version, name, description) VALUES ((SELECT id FROM services WHERE name = 'Security'), '1.0.0', 'Initial version of Security service', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nunc nec odio tincidunt aliquam. Sed nec nunc nec odio tincidunt aliquam.');
