services:
  kong-database:
    image: postgres:12-alpine
    restart: always
    shm_size: 128mb
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - ./kong-database:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    container_name: kong-database
    networks:
      - kong-network

  kong-api:
    build:
      context: ../kong-apis-portal
      dockerfile: Dockerfile
    # image: kong-apis-portal
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    environment:
      - APP_AUTH_SECRET=secret
      - APP_AUTH_EXPIRES_IN=1d
      - APP_AUTH_PASSWORD_SALT=secret
      - DB_HOST=kong-database
      - DB_PORT=5432
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_NAME=kong
      - DB_SCHEMA=public
    depends_on:
      - kong-database

    container_name: kong-apis-portal
    networks:
      - kong-network

  kong-api-golang:
    build:
      context: ../kong-apis-portal-golang
      dockerfile: Dockerfile
    # image: kong-apis-golang
    ports:
      - 3001:3001
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
    environment:
      - APP_AUTH_SECRET=secret
      - APP_AUTH_EXPIRES_IN=1d
      - APP_AUTH_PASSWORD_SALT=secret
      - DB_HOST=kong-database
      - DB_PORT=5432
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_NAME=kong
      - DB_SCHEMA=public
    depends_on:
      - kong-database
    container_name: kong-apis-golang
    networks:
      - kong-network

networks:
  kong-network:
    external: true
    driver: overlay
    name: kong-network
